#!/usr/bin/env bash 
# https://devilgate.org/blog/2012/07/02/tip-using-pandoc-to-create-truly-standalone-html-files
: "${PATH_BASE:="$(git rev-parse --show-toplevel)"}" 
cd "${PATH_BASE}"/content
# https://github.com/pandoc/dockerfiles
for path_dir in $(find -type d -name "*" 2>/dev/null); do
  path_readme="${path_dir:2}"
  file_readme="${path_dir:2}"/README.md
  if [[ -f "${file_readme}" ]]; then
    title=$(basename $(dirname "${file_readme}")) 
    echo "title: ${title}" 
    echo "file_readme: ${file_readme}" 
    echo $(
      docker run \
        --rm \
        --volume "`pwd`:/data" \
        --volume "${PATH_BASE}/css":"/css" \
        pandoc/core:latest \
          --standalone \
          --metadata pagetitle="${title}" \
          --highlight-style haddock \
          -f markdown+hard_line_breaks \
          -t html5 \
          -H /css/github1.css \
          "${file_readme}"
    ) > "${path_readme}"/index.html
        # pandoc/latex:2.6 \
          # -H /css/github1.css \
          # -t slidy \
          # --wrap=preserve \
  fi 
done
