#!/usr/bin/env sh 
date_formatted=$(date "+%Y.%m.%d %H:%M")
git add -A
git commit -m "[publish] ${date_formatted}"
git push origin master

hcloud context use divramod.io
ip=$(hcloud server list | tail -n +2 | awk '{ print $4; }')
ssh -o "StrictHostKeyChecking no" root@"${ip}" '
  cd /var/www/divramod.io &&
  git stash &&
  git pull origin master &&
  direnv allow &&
  cp /var/www/divramod.io/conf/nginx/divramod.io /etc/nginx/sites-enabled &&
  systemctl restart nginx &&
  /var/www/divramod.io/scripts/dio_render
'
